# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: dataicer actions

on: [push, pull_request]

jobs:

  build-test:
    name: Build and test dataicer
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.8', '3.9', '3.10']
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Run tests
      run: |
        pytest -v

    - name: Build wheels
      run: pip wheel . -w dist --no-deps

  test-publish:
    name: Publish to test.PyPI
    runs-on: ubuntu-latest
    needs: [build-test]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.PYPI_UNAME_TOKEN }}
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-test]

    # If this is a tagged release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.PYPI_UNAME_TOKEN }}
        password: ${{ secrets.PYPI_API_TOKEN }}
